version: "3.9"

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack
    environment:
      - DEBUG=0
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./lambda:/lambda"
      - "./data:/data"
      - ./localstack-scripts:/opt/code/localstack/scripts
